name: Tests regsmart
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  REGSMART_PACKAGE: "git+https://github.com/leticosta4/pytest-regsmart@e8fe612271bc27698cd8285a535209262e8e1a03"

jobs:

  tests:
    name: regsmart (${{ matrix.mode }})
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: rgsm_qtf
            weight: "1-0"
          - mode: rgsm_recentfail
            weight: "0-1"
          - mode: rgsm_hybrid
            weight: "1-1"
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Python (3.12)
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: pyproject.toml
    - run: uv pip install -e ".[dev]" --system

    - name: Install pytest-regsmart
      run: |
        uv pip install --system "$REGSMART_PACKAGE"
        uv pip freeze --system

    - name: Restore pytest-regsmart cache
      id: restore-pytest-regsmart-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/.pytest_cache/v/pytest_ranked_selection_data
        key: pytest-regsmart-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.mode }}
        restore-keys: |
          pytest-regsmart-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.mode }}-

    - name: run tests (py312)
      timeout-minutes: 40
      env:
        PYTHONUTF8: 1
      run: >
        pytest --regsmart --ranking-weight=${{ matrix.weight }} -n=logical --dist=worksteal --timeout=300 --durations=0
        --cov --cov-report=xml --cov-report=term
        #talvez eu tire essa flag de cov ainda

    - name: Save pytest-regsmart cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/.pytest_cache/v/pytest_ranked_selection_data
        key: pytest-regsmart-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.mode }}-${{ github.run_id }}
